version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    container_name: spring-bookstore-mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstore
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=rootpassword"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    image: spring-bookstore-app
    container_name: spring-bookstore-app
    build:
      context: .
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/bookstore
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      mysqldb:
        condition: service_healthy
