version: '3.8'

services:
  mysqldb:
    image: mysql:8
    container_name: spring-bookstore-mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    networks:
      - spring-bookstore-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-bookstore-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    depends_on:
      - mysqldb
    networks:
      - spring-bookstore-network

networks:
  spring-bookstore-network:
    driver: bridge
